version: '2.15.1'

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5670:5670'
      - '5671:5671'
    networks:
      - rabbitmq_network
  
  producer:
    build: 
     context: ./producer
     dockerfile: Dockerfile
    ports:
      - '5100:5100'
    networks:
      - microservices_network
    
  consumer_one:
    build:
     context: ./consumer_one
     dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1

    networks:
      - microservices_network

  consumer_two:
    build: 
     context: ./consumer_two
     dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - microservices_network

  consumer_three:
    build: 
     context: ./consumer_three
     dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
  
    networks:
      - microservices_network

  consumer_four:
    build: 
     context: ./consumer_four
     dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1

    networks:
      - microservices_network


  
  mongodb:
    image: mongo
    expose:
      - 5187

networks:
  microservices_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge
